### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by seamusjunior** [kroonwijk/Orchard.AngularJS#5]
Is there any actual example modules that actually use this?

**Comment by BenedekFarkas** [comment]
Hi! It's not issue, so I'll close it.

I don't know about any particular examples for this, but you can use the resources of this module like any other Orchard resource declared through a ResourceManifest, e.g.
```csharp
Script.Require("AngularJS").AtFoot();
```
or use it as a dependency of your own resources.
